/*
* Library that scrolls messages on a small (<32 columns) array of LEDs
*
* N.B.
*  - The timing constants are all scaled to a standard ESP8266 clock
*     * change them when running at different clock speed
*  - Fonts are built-in and generated by fontgen.c
*/

// TODO
//  * add OE pin to the constructor
//  * add blink mode option

#ifndef LED_ARRAY_H
#define LED_ARRAY_H

#include <ShiftRegister74HC595.h>
#include "fonts.h"


#define LIB_VERSION     "1.0"
#define STD_WAIT        100 //50
#define LONG_WAIT       2000


class LedArray {
public:
    String libVersion = LIB_VERSION;

    LedArray(byte dataPin, byte srClkPin, byte rClkPin, byte numRows, byte numCols, byte numSRs, int scrollSpeed);

    void clear();
    void fill(uint32_t val);
    void fill(uint32_t vals[]);
    void run();
    //// TODO add getFonts() -- return number and description of each font
    void message(String str, byte fontNumber);
    void appendMessage(String str, byte fontNumber);

private:
    int stdWaitCycles;
    int waitCycles;
    byte fontNumber;

    byte numRows;
    byte numCols;
    int numSRs;

    //// FIXME figure out how to initialize this
    ShiftRegister74HC595 *srPtr;

    // active high bitmap, row pixels start at the LSB, [0,0] is upper left corner
    uint32_t *frameBufferPtr;

    // string to be displayed
    String message;

    int loopCount = 0;
    int curChar = 0;
    byte curCol = 0;

    void writeToFB(char *strPtr);
    void scrollMessage();
    void scanDisplay();
}

#endif /*LED_ARRAY_H*/